src/capi/azext_capi/custom.py
Fixes a bug in writing the workload cluster kubeconfig file.
---
=> Fix writing of kubeconfig file

src/capi/azext_capi/_params.py, src/capi/azext_capi/tests/latest/test_capi_scenario.py
Adds a heavily mocked unit test for `az capi show`. This should be a template for fleshing out UTs for the rest of the commands.
---
=> Add unit test for "az capi show"

.coveragerc, .github/workflows/build.yml, .vscode/settings.json, requirements.txt, src/capi/azext_capi/tests/latest/test_capi_scenario.py
Adds a unit test for "az capi show" and create a .coverage file when running unit tests in GH actions.
This isn't hooked up to coverage tracking or an online coverage report (yet).
---
=> Add unit test and code coverage report

src/capi/azext_capi/_params.py, src/capi/azext_capi/custom.py
Smooths out the happy path (with `--yes`) so it ends with a workload cluster's kubeconfig being written locally.
---
=> Retry fetching kubeconfig when creating workload cluster

src/capi/azext_capi/_format.py, src/capi/azext_capi/custom.py
Adds the "phase" column to `az capi show|list -o table`, similar to `kubectl get clusters -o table`.
---
=> Add phase to table view of clusters

src/capi/azext_capi/custom.py, src/capi/azext_capi/tests/latest/test_capi_scenario.py
Add user confirmation to `az capi management delete|update` and `az capi delete` by default. The `--yes|-y` flag can be used to skip it.
Fixes #33
---
=> Add user confirmation to several commands

src/capi/HISTORY.rst, src/capi/azext_capi/custom.py
Captures stdout/stderr from wrapped command tools and replaces with a high-level summary of tasks with indeterminate progress spinners.
Fixes #30 
For example:
```shell
% az capi create -n testcluster1 -l southcentralus -y                     
Command group 'capi' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
✓ Generated workload cluster configuration at "testcluster1.yaml"
✓ Downloaded kubectl
✓ Downloaded clusterctl
✓ Downloaded kind
✓ Created local management cluster "capi-manager"
✓ Initialized management cluster
✓ Created workload cluster "testcluster1"
✓ Workload cluster is accessible
✓ Workload access configuration written to "testcluster1.kubeconfig"
✓ Deployed CNI to workload cluster
✓ Workload cluster is ready
{ …
```
=> Rework UX for "az aks create" as a checklist

.gitignore, src/capi/azext_capi/custom.py
PackageLoader was blowing up trying to find "azext_capi.custom" rather than "azext_capi". I've just change the loader to use a static string rather than `__name__`.
```
$ az capi create -n foo
Command group 'capi' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
The command failed with an unexpected error. Here is the traceback:
The 'azext_capi.custom' package was not installed in a way that PackageLoader understands.
Traceback (most recent call last):
File "/home/david/code/azure/azure-capi-cli-extension/venv/lib/python3.9/site-packages/knack/cli.py", line 231, in invoke
cmd_result = self.invocation.execute(args)
File "/home/david/code/azure/azure-capi-cli-extension/venv/lib/python3.9/site-packages/azure/cli/core/commands/__in …
```
=> change package loader from dynamic name to static string

src/capi/azext_capi/tests/latest/test_capi_scenario.py
Adds an explicit `--output json` argument to `az` commands in unit tests, so they succeed even if `~/.azure/config` specifies a different default output format.
N/A
---
=> Fix unit tests when default az output isn't JSON

src/capi/azext_capi/custom.py
The command-line spinner animation wasn't exiting cleanly in the case where an error was raised. This fixes that.
N/A
---
=> Fix a spinner exit bug

src/capi/azext_capi/custom.py
When I was looking at `custom.py`, the VS Code highlighter showed me two arguments to `create_workload_cluster` that were unused but should have been passed through to the Jinja templates. This fixes that.
---
=> Add two variables that weren't being templated

src/capi/azext_capi/_help.py, src/capi/azext_capi/custom.py
Pr aims to update Jinja Templating behavior to raise errors if variables are missing to prevent generating invalid templates
Fixes:  #69 
---
=> Change Jinja behavior to raise error on template rendering

src/capi/azext_capi/custom.py, src/capi/azext_capi/tests/latest/test_capi_scenario.py
The current method `az capi management create` to create a management cluster only works if there is an existent k8s cluster and installing the required capz components.
The update aims to allow user to decide if they want to use existing cluster aa a management cluster or to create a management cluster from scratch.
User scenarios:
1. User decides to use existing cluster as a management cluster, we check if we have access to the cluster and proceed to install capz components.
2. User selects to create cluster from scratch, they have the option to create a local (kind) or AKS cluster.
The logic for prompting the user and creating management is extracted to a helper method as it can be reused in `az capi create` when we need to create a management cluster  …
=> Updated create management cluster method

src/capi/azext_capi/custom.py
This PR aims to fix an exception not being caught when we fetch for a not existing resource group in `az capi create` method
The supposed behavior is intended to look for a resource group if user specifies one with flag `-g or --resource-group` or allow CAPZ create one when it is needed.
At the moment if the group is not found it will raise an exception that is not handle and therefore the process is terminated.
Fixes #68
---
=> updated exception handle of resource group finding attempt

src/capi/azext_capi/_help.py, src/capi/azext_capi/custom.py, src/capi/azext_capi/tests/latest/test_capi_scenario.py
This PR aims to allow users to custom name their management cluster instead of only the hardcoded name "capi-manager"
when running `az capi management create` and `az capi create`.
This is presented to the user in two options:
1. Use flag `--cluster-name` for `az capi management create` and `--management-cluster-name` for `az capi create`
2.  When a user is creating the management cluster, they will be prompt if they want to custom name the cluster or default it.
Fixes:  #71 
---
=> Allow custom naming a management cluster

src/capi/azext_capi/_help.py, src/capi/azext_capi/_params.py, src/capi/azext_capi/custom.py, src/capi/azext_capi/tests/latest/test_capi_scenario.py
This PR aims to cover and update, the UX of creation an Aks management cluster:
This update aims to allow user customization of Aks management cluster name, resource group name, location and resource group.
- This is accomplished by an updated UX flow in which we prompt user for customize names or they can default it.
- The users can also utilize new flags on methods `az capi create` & `az capi management create`  
az capi create new flags:
```
--management-cluster-name 
--management-cluster-resource-group-name -mg
```
az capi  management create new flags:
```
--cluster-name 
--location -l
--resource-group -g
```
To note that users can skip prompts for custom values by entering an empty value or by using the `--yes` flag when running the command.
Fixes #78 
**History …
=> Update UX of creating Aks management cluster 

src/capi/azext_capi/_help.py, src/capi/azext_capi/_helpers.py, src/capi/azext_capi/custom.py, src/capi/azext_capi/tests/latest/test_helpers.py
This PR aims to add pivot functionality to `az  capi create` with flag `--pivot`.
The current will take care of 
1. Creating a temporal bootstrap management cluster 
2. Creating a workload cluster
3. Installing Cluster API components in workload cluster
4. Waiting for components to be running
5. Proceed to move Cluster Objects from bootstrap cluster to workload cluster
6. After successfully moved the objects, we will delete temporal bootstrap cluster
7. Merge default kubeconfig with workload kubeconfig so we can continue to refence workload cluster.
***Note***: Delete management cluster, when deleting kind cluster mostly everything gets clean by `kind delete cluster` including context in kubeconfig. However, for AKS, the kubeconfig context get left behind. We are taking …
=> added pivot option for capi create

src/capi/azext_capi/_help.py, src/capi/azext_capi/_params.py, src/capi/azext_capi/commands.py, src/capi/azext_capi/custom.py
Add a separate install tools command. This allows for something like `sudo az capi install` which fixes issues when installing things on Linux.  This seems to be the pattern according to https://github.com/Azure/azure-cli/issues/2558#issuecomment-289919156
Fixes: #90 
Something I tried was using a temp path in the function `download_binary` if on linux but because this command was in a spinner it never prompted (it did but it got overwritten). It worked if I had recently used sudo.
```
if system == "Linux":
tmpfile = Path(tempfile.gettempdir()).joinpath(os.path.basename(install_location))
urlretrieve(file_url, tmpfile)
os.system(f"sudo mv {tmpfile} {install_location}")
else:
```
---
This checklist is used to make sure that common guidelines for an Azure …
=> Add a separate install tools command

src/capi/azext_capi/custom.py, src/capi/azext_capi/templates/KubeadmConfigTemplate.yaml
This PR aims to fix an exception being raised by failing jinja rendering windows templates validation.
When rendering window templates, we were using `AZURE_SSH_PUBLIC_KEY` which was not passed to jinja arguments and failed validation.  
Updating `AZURE_SSH_PUBLIC_KEY_B64` to `AZURE_SSH_PUBLIC_KEY`
Fixes #91 
---
=> Update AZURE_SSH_KEY on jinja templates

src/capi/azext_capi/custom.py, src/capi/azext_capi/tests/latest/test_capi_scenario.py
This PR aims to added support for deleting a self-managed workload cluster on `az capi delete`
to delete a self-managed cluster, need to use `--resource-group/-g`
This implementation goes the route of directly deleting the resource group of workload cluster.
Instead of creating a temporal management cluster and moving the workload cluster to be deleted into this temporal cluster and issuing delete command to the workload cluster and deleting temporal management cluster.
There is assumption about deleting the resource group of workload cluster.
@mboersma Do you think we should inform or/and ask for confirmation about deleting the entire resource group to the user?
---
This checklist is used to make sure that common guidelines for an Azure CLI pull request …
=> Update capi delete to work for self-managed clusters

src/capi/azext_capi/helpers/binary.py
This PR aims to add extra validation to check for docker when installing kind.  To prevent failures when using kind if pre-requirements were not found.
Fixes #101 
---
=> add docker as kind's pre-requirement check

src/capi/azext_capi/custom.py, src/capi/azext_capi/tests/latest/test_capi_scenario.py
Fixes #59
The general process for updating these two fixtures is to actually provision a couple of workload clusters, then capture the output of `az capi list` and `az capi show` as JSON. Paste it into the test file in the right place and remove the incorrectly escaped `last-applied-configuration` value so it parses correctly.
---
=> Update test fixtures for v1beta1

src/capi/azext_capi/_format.py, src/capi/azext_capi/custom.py, src/capi/azext_capi/tests/latest/test_capi_scenario.py
Fixes #26
Before:
```shell
% az capi list -o tsv
v1	2	List
% az capi show -n testcluster1 -o tsv
cluster.x-k8s.io/v1beta1	Cluster
```
After:
```shell
% az capi list -o tsv                
2022-05-27T20:53:08Z	default-4377	default	Provisioned
2022-05-27T20:58:06Z	testcluster1	default	Provisioned
% az capi show -n testcluster1 -o tsv
2022-05-27T20:58:06Z	testcluster1	default	Provisioned
```
---
=> Improve tab-separated output for capi show and list

src/capi/azext_capi/helpers/kubectl.py, src/capi/azext_capi/helpers/run_command.py
This PR aims to fix writing kubeconfig file with warning message on it
To get the kubeconfig of a workload cluster we are running ` clusterctl get kubeconfig <cluster-name>` through `run_shell_command` this method combines `STDERR & STDOUT` by default.
The approach to this fix is allow option to no combine `STDERR & STDOUT`
Fixes #137
---
=> Fixed writing kubeconfig file

src/capi/azext_capi/custom.py, src/capi/azext_capi/tests/latest/test_capi_scenario.py
This PR aims to update the current behavior of `az capi management delete` to a more expected behavior of deleting the management cluster on its entirety. Instead of just removing CAPI components out of the cluster
See #133
---
=> Update `capi management delete` behavior

src/capi/azext_capi/_help.py, src/capi/azext_capi/custom.py, src/capi/azext_capi/helpers/names.py, src/capi/azext_capi/tests/latest/test_capi_scenario.py, src/capi/azext_capi/tests/latest/test_helpers.py
Changes the behavior of `az capi create` so if no `--name` argument is provided, it generates a random one:
```shell
% az capi create -l westus3
Command group 'capi' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
Using generated cluster name "lively-lakeside"
...
```
Fixes #119
cc: @nawazkh
This code was adapted from deis-controller code I wrote ten years ago. I believe this reuse is legitimate since:
- the origin and target codebases are both MIT-licensed
- all code and IP of Deis was transferred to Microsoft upon acquisition
az capi create: add random cluster name generator
---
=> Add random cluster name generator

src/capi/azext_capi/_help.py, src/capi/azext_capi/custom.py, src/capi/azext_capi/tests/latest/test_capi_scenario.py
Hi, this closes #120.
When --location isn't specified, it's now determined by:
1. config file [defaults]
2. resource-group
3. AZURE_LOCATION
4. still None -> raise RequiredArgumentMissingError
Did I miss anything?
Edit: actually when i think about it, maybe it makes more sense to have config file [defaults] and AZURE_LOCATION both either before resource-group or both after..
=> Add `AZURE_LOCATION` as default `--location` in `capi create`

.github/workflows/nightly.yml, .gitignore
Signed-off-by: James Sturtevant <jstur@microsoft.com>
Allows for using changes from the main branch in testing.
I got this working on my fork: https://github.com/jsturtevant/azure-capi-cli-extension/releases/tag/az-capi-nightly
---
=> Add nightly build

src/capi/azext_capi/_help.py, src/capi/azext_capi/_params.py, src/capi/azext_capi/custom.py, src/capi/azext_capi/helpers/binary.py
In some environments, users won't have access to /usr/local/bin. This PR adds the `--install-path -ip` flag to `az capi install` so users can specify a specific installation path for binaries.
Fixes #16 
az capi install: Add --install-path flag
---
=> Add configurable install path for binaries

src/capi/azext_capi/custom.py, src/capi/azext_capi/tests/latest/test_capi_scenario.py
When creating an AKS management cluster, we would `az group create` over the top of an existing RG, which deletes its tags. This changes so we check first and skip that if the RG exists.
---
=> Don't recreate the resource group for AKS

src/capi/azext_capi/_help.py, src/capi/azext_capi/_params.py, src/capi/azext_capi/custom.py, src/capi/azext_capi/helpers/kubectl.py
This PR adds an option flag `--wait-for-nodes` to `az capi create` which adds an extra step to wait for all the workload nodes to be created before exiting. The command currently returns as soon as the control plane is available, and ignores if errors happen to any workload nodes. Fixes #158 
---
=> Add --wait-for-nodes flag

src/capi/azext_capi/custom.py, src/capi/azext_capi/tests/latest/test_capi_scenario.py
The `check_resource_group` function was being called from AKS mgmt cluster creation, but that invocation apparently expected it to raise exceptions that it does not. I refactored it to return a boolean, which seems to fix `az aks create -y` in my testing. I also fixed some related unit tests to work regardless of `AZURE_LOCATION` being set.
---
=> Fix resource group check

src/capi/azext_capi/custom.py, src/capi/azext_capi/helpers/kubectl.py
`az capi create` had two separate phases of "Waiting for nodes". This collapses them into one and removes some unused code.
---
=> Simplify waiting for nodes

src/capi/azext_capi/helpers/kubectl.py
We noticed that for windows clusters, it takes a longer time for nodes to come up as ready. We are increasing the timeout to 15 minutes because of this issue.
Increase wait_for_number_of_nodes timeout to 15 minutes
---
=> Increase wait_for_number_of_nodes timeout to 15 minutes

src/capi/azext_capi/_completers.py
Tab completion for the `--name|-n` parameter broke silently because `cmd` was `None`.
The completer's code path from `get_workflow_clusters_completion_list` ends up calling the `tab_separated_output` function which references `cmd.cli_ctx`. This presumably raised an error which was swallowed by the CLI framework. Passing the `cmd` through  works.
---
=> Fix tab completion for --name

src/capi/azext_capi/custom.py, src/capi/azext_capi/helpers/os.py, src/capi/azext_capi/tests/latest/test_helpers.py
The `az aks get-credentials` command quits with an error if some default entries aren't present in the user's kubeconfig file. This works around that, since `az capi` shells out to that command.
---
=> Fix case where "az aks" errors on empty kubeconfig

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .github/workflows/build.yml, .github/workflows/nightly.yml, README.md, src/capi/setup.py
CI recently began failing because Python 3.6 is no longer supported. This updates the GH actions we use and bumps the python version support to 3.7 - 3.11.
---
=> Update GitHub actions and python versions

src/capi/azext_capi/helpers/binary.py, src/capi/azext_capi/tests/latest/test_helpers.py
The implementation of `install_helm` naively passed python's `platform.machine()` through as the `$(ARCH)` for downloading. This helper method returns the more likely build architectures found in binary download packages, and fixes a couple other helpers to take architecture into account.
---
=> Fix install_helm to handle x86_64 arch

src/capi/HISTORY.rst, src/capi/azext_capi/_help.py, src/capi/azext_capi/_params.py, src/capi/azext_capi/custom.py
Changes the `--wait-for-nodes` argument to `az capi create` from a boolean to an integer defaulting to 1, and removes the default control_plane_node_count + workload_node_count calculation.
This puts more burden on the user to be explicit about their cluster size and shape, but we think in many cases the default logic described above would fail, so it needs to be customizable. Redefining the existing argument a bit avoids adding yet another one.
```
az capi create: make --wait-for-nodes a user-supplied integer
```
---
=> Make --wait-for-nodes a user-supplied integer

src/capi/azext_capi/helpers/kubectl.py
The polling for the workload cluster's kubeconfig was accidentally printing to stdout even without the `--debug` flag.
Fixes #142
---
=> Hide clusterctl output unless --debug

src/capi/azext_capi/helpers/binary.py
The `install_kind` function defaulted to an old version and wasn't taking into account the platform architecture. This fetches the latest official release for the correct architecture.
I would default to "latest" instead of hard-coding a version, but that gets us a prerelease version:
```shell
% ./env/bin/kind version                                    
kind v0.18.0-alpha+7d26b50a129faf go1.19.3 darwin/arm64
```
I think it's safer to pin to a known-working version and update periodically than to use alpha builds of `kind`.
I've tested this locally.
---
=> Improve kind install helper

src/capi/HISTORY.rst, src/capi/azext_capi/custom.py, src/capi/setup.py
The Windows kube-proxy manifest was being prepared but not applied.
Fix: apply Windows kube-proxy manifest
---
=> Apply Windows kube-proxy manifest

src/capi/azext_capi/custom.py
Reported by @huntergregory
> It seems az capi create is currently failing with the [newest capi extension version](https://github.com/Azure/azure-capi-cli-extension/releases). It seems this commit removed a file resulting in a 404 error.
[Remove Calico felix override workaround · kubernetes-sigs/cluster-api-provider-azure@34c05f8 (](https://github.com/kubernetes-sigs/cluster-api-provider-azure/commit/34c05f84d17b65ab357cd2ef074c9ddae2d20eb8)[github.com](http://github.com/)[)](https://github.com/kubernetes-sigs/cluster-api-provider-azure/commit/34c05f84d17b65ab357cd2ef074c9ddae2d20eb8)
cli: ✓ Deployed CNI to workload cluster
cli: Applying felix-override manifest.
error: unable to read URL "https://raw.githubusercontent.com/kubernetes-sigs/cluster-api-provider-azure/main/temp …
=> Remove Felix override workaround

src/capi/HISTORY.rst, src/capi/azext_capi/custom.py
Signed-off-by: Mark Rossetti <marosset@microsoft.com>
Updating az capi to be able to deploy KPNG on windows instead of in-tree kube-proxy
Updating az capi to be able to deploy KPNG on windows instead of in-tree kube-proxy
---
=> Updating az capi to be able to deploy KPNG on windows instead of in-tree kube-proxy

src/capi/HISTORY.rst, src/capi/azext_capi/custom.py, src/capi/setup.py
Pins the Calico manifests at a known-working version of CAPZ.
Pin calico manifests at CAPZ release-1.7
---
=> Pin Calico manifest at 1.7

create-dev-env.sh, requirements.txt
Changes to the `azdev` CLI developer tool in v0.1.49 broke our CI and local development workflow:
```shell
% azdev                     
[Errno 2] No such file or directory: '_NONE_/scripts/ci/cmdcov.yml'
```
This pins `azdev` to known-working version v0.1.48.
See Azure/azure-cli-dev-tools#407
---
=> Pin to working version of azdev

src/capi/HISTORY.rst, src/capi/azext_capi/custom.py, src/capi/azext_capi/templates/KubeadmConfig.yaml, src/capi/azext_capi/templates/KubeadmControlPlane.yaml
Sets `--external-cloud-provider=true` as the default to `az capi create`. It's time; without this, Kubernetes v1.29.x clusters won't work.
Fixes #188
`--external-cloud-provider=true` is now the default for `az capi create`
---
=> Default to external cloud provider

src/capi/azext_capi/helpers/network.py
Follows best practices when creating an SSL context in Python, now that we don't need to worry about Python 2 support. Also closes a security alert for project maintainers: 
https://github.com/Azure/azure-capi-cli-extension/security/code-scanning/7
=> Update SSL download context to avoid broken ciphers

src/capi/HISTORY.rst, src/capi/azext_capi/helpers/kubectl.py, src/capi/azext_capi/helpers/run_command.py, src/capi/azext_capi/tests/latest/test_helpers.py, src/capi/setup.py
Allows commands to specify certain output fields to be masked, so their values will appear in log output as `"****"`. This mechanism works for the `--verbose` and `--debug` flags for commands, assuming JSON or YAML-type output.
Fixes #248 
az capi: Mask sensitive data values in --verbose or --debug log output
---
=> Mask specified log output

src/capi/azext_capi/helpers/run_command.py
Fixes a big bug in the implementation of `mask()` that could munge the actual data, when the intention was only to mask logged output.
---
=> Fix mask implementation to change only log
