Azure/azure-capi-cli-extension

- src/capi/azext_capi/_client_factory.py
- src/capi/azext_capi/_completers.py
- src/capi/azext_capi/_help.py
- src/capi/azext_capi/_params.py
- src/capi/azext_capi/custom.py
> Improve arg help and add some tab completers

- src/capi/azext_capi/commands.py
- src/capi/azext_capi/custom.py
> Install CNI and loop and wait for commands to complete

- src/capi/azext_capi/_help.py
- src/capi/azext_capi/_params.py
> Remove -v short alias for --vnet-name flag

- src/capi/azext_capi/_help.py
- src/capi/azext_capi/custom.py
- src/capi/azext_capi/tests/latest/recordings/test_capi_create.yaml
- src/capi/azext_capi/tests/latest/test_capi_scenario.py
> Improve validation of RG and location flags

- src/capi/azext_capi/__init__.py
- src/capi/azext_capi/_completers.py
- src/capi/azext_capi/_helpers.py
- src/capi/azext_capi/custom.py
> Fix install of clusterctl tool

- .gitignore
- .vscode/example-launch.json
> Added example of launch.json debug configuration

- src/capi/azext_capi/_completers.py
- src/capi/azext_capi/_params.py
- src/capi/azext_capi/custom.py
- src/capi/azext_capi/tests/latest/test_capi_scenario.py
The code hasn't been updated in a while and seems to have rusted: a test package import has moved elsewhere and `azdev style` has some fresh complaints. This PR fixes both.
N/A
---
> Fixed linter complaints and a test import

- src/capi/azext_capi/custom.py
As part of #46, this makes the default management cluster mode "azure" and renames "kind" to "local". This is to abstract away the implementation of using AKS as the management cluster or kind as the local management cluster, simply giving users the choice between building a management cluster locally on their machine or deploying one in Azure.
---
> make azure management cluster the default

- src/capi/azext_capi/custom.py
A small refactor to extract logic of binary downloading for reusability. 
---
> Refactor - Extract Binary Downloading as helper function

- src/capi/azext_capi/custom.py
Updating validation of finding management cluster within different namespaces 
---
> Update validations for finding management cluster

- src/capi/azext_capi/custom.py
This pr aims to change the way that we handle missing azure env variables. Currently If we are missing multiple variables the extension will inform you of the first missing variable. This aims to improve UX as it will inform user of all missing azure env variables at once, preventing the user to do multiple restarts to set all missing variables.
Fixes: #67
---
> Change raising error for all missing azure env variables at once

- src/capi/azext_capi/custom.py
- src/capi/azext_capi/tests/latest/test_capi_scenario.py
This pr aims to update `az capi create` command to work with aks management cluster.
Aims to fix:
1. Losing reference to aks management cluster:
After we created our aks management clusters, we lose the refence to the cluster.  Now to regain proper reference, we are getting aks credentials afterwards. 
2. AAD Pod Identity having conflicts on aks management cluster:
When we install the capz components into our aks management cluster, we are installing AAD Pod Identity. However our management cluster was defaulting to kubenet as its k8s network plugin. [Kubenet no longer has default support for ADD](https://azure.github.io/aad-pod-identity/docs/configure/aad_pod_identity_on_kubenet/) due to some security concerns . So now we updated to azure CNI as our network plugin.
In …
> Update capi create to work with aks management cluster

- src/capi/azext_capi/tests/latest/test_capi_scenario.py
- src/capi/azext_capi/tests/latest/test_helpers.py
This PR aims to update the test structure for a better organization and separation of test cases with the goal to allow easier debugging and maintainability by using test classes to group relevant test and decouple test cases into different methods within each class.
---
> updated tests structure

- src/capi/azext_capi/custom.py
- src/capi/azext_capi/tests/latest/test_helpers.py
This PR aims to remove a big assumption of using default cluster found in current context without verification of user when running `capi create`.
Now we will inform user that we have found a cluster:
If the cluster has CAPI components installed will prompt the user if they want to use this management cluster.
If the cluster does not have CAPI components will ask user if they want to use this cluster as the management cluster if so, we will install required components.
If no cluster is found, we will prompt user for creation of one.
Fixes #84
---
> Update Handle of find and using k8 cluster as Management Cluster in capi

- .github/workflows/build.yml
- src/capi/HISTORY.rst
- src/capi/azext_capi/helpers/__init__.py
- src/capi/azext_capi/helpers/binary.py
- src/capi/setup.py
Adds `__init__.py` to the helpers directory to mark it as a proper Python package.
Fixes #103
---
> Add package marker file to helpers

- src/capi/azext_capi/_help.py
Updating the long-summary field of the --template argument help description to fix https://github.com/Azure/azure-capi-cli-extension/issues/121
---
> update long-summary field for template

- src/capi/HISTORY.rst
- src/capi/azext_capi/custom.py
- src/capi/azext_capi/helpers/binary.py
- src/capi/azext_capi/helpers/kubectl.py
- src/capi/azext_capi/helpers/os.py
- src/capi/azext_capi/helpers/run_command.py
Uses Helm to install Calico CNI on workload clusters.
```
Install Calico with Helm on workload clusters
```
---
> Install Calico with Helm on workload clusters

- src/capi/azext_capi/helpers/kubectl.py
`az capi` is very terse by design, unless you run with the `--debug` flag, in which case all command input and output are echoed.
Waiting for nodes using `kubectl get nodes -o json` wastes a huge amount of real estate on the screen or in the logs, and isn't necessary since we're just counting the number of `Ready` nodes. This PR changes it to this:
```shell
cli: kubectl get nodes --no-headers --kubeconfig flaxen-milepost.kubeconfig returned:
flaxen-milepost-control-plane-g9tkr   Ready      control-plane   2m36s   v1.25.3
flaxen-milepost-md-0-lqrc8            NotReady   <none>          14s     v1.25.3
cli: kubectl get nodes --no-headers --kubeconfig flaxen-milepost.kubeconfig returned:
flaxen-milepost-control-plane-g9tkr   Ready      control-plane   2m41s   v1.25.3 …
```
> Don't echo JSON while waiting for nodes with --debug

- src/capi/azext_capi/custom.py
> Fix resource group creation prompt

- src/capi/azext_capi/custom.py
Fixes a bug in the CIDR swapping logic in the case they show up as (ipv6, ipv4).
---
> Fix CIDR swapping logic

- .github/workflows/nightly.yml
Syncs up the nightly.yml GH actions with the updated ones in build.yml.
---
> Update nightly build GH actions

- .devcontainer/library-scripts/docker-in-docker-debian.sh
- src/capi/HISTORY.rst
- src/capi/setup.py
Updates the Docker-in-Docker setup script from the [vscode-dev-containers project](https://github.com/microsoft/vscode-dev-containers/tree/main/containers/docker-in-docker/.devcontainer/library-scripts) to fix a bug running CodeSpaces in local VS Code.
Fixes #154
Update docker-in-docker script for CodeSpaces
---
> Update docker-in-docker script for CodeSpaces

- src/capi/azext_capi/custom.py
Read infra rg and vnet name via get function to avoid crashes when using existing management cluster
Read infra rg and vnet name via get function to avoid crashes when using existing management cluster
---
> Read infra rg and vnet name via get function

- src/capi/azext_capi/custom.py
- src/capi/azext_capi/helpers/run_command.py
- src/capi/azext_capi/tests/latest/test_helpers.py
Some small and medium refactorings to make usage of the Spinner simpler, and to make `custom.py` smaller.
Fixes #185
---
> Refactor custom.py and spinner helpers

- .github/workflows/nightly.yml
Hopefully fixes permissions errors we've seen recently with the nightly GH action.
---
> Update permissions for nightly GH action

- .devcontainer/Dockerfile
- .devcontainer/library-scripts/docker-in-docker-debian.sh
- requirements.txt
Pins python and Docker versions as recommended by the security scanner.
> Pin dependencies

- .flake8
- src/capi/azext_capi/_client_factory.py
- src/capi/azext_capi/_completers.py
- src/capi/azext_capi/_format.py
- src/capi/azext_capi/_params.py
- src/capi/azext_capi/custom.py
- src/capi/azext_capi/helpers/binary.py
- src/capi/azext_capi/helpers/constants.py
- src/capi/azext_capi/helpers/kubectl.py
- src/capi/azext_capi/helpers/logger.py
- src/capi/azext_capi/helpers/names.py
- src/capi/azext_capi/helpers/network.py
- src/capi/azext_capi/helpers/os.py
- src/capi/azext_capi/tests/latest/test_helpers.py
Trying to fix new linter errors that cropped up, presumably as `azdev` and other tools have been updated.
---
> Fix new linter errors
